# Generated by Django 4.0.6 on 2023-01-23 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=64)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=11)),
                ('country', models.CharField(max_length=64)),
                ('postcode', models.CharField(max_length=7)),
                ('town', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('street_name', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=5)),
                ('date', models.DateField(auto_now_add=True)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('payment_due', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('payed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='orderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('orderitem_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderItem', to='checkout.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
