# Generated by Django 4.0.6 on 2023-01-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_userdetails_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='house_number',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
    ]
