# Generated by Django 4.0.6 on 2023-01-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_userdetails_house_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
