# Generated by Django 4.0.6 on 2023-01-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_userdetails_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
