# Generated by Django 4.0.6 on 2023-01-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_alter_userdetails_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='house_number',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
