# Generated by Django 4.0.6 on 2023-01-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
